apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: apptestlevilugatohpa

spec:
 scaleTargetRef:
   apiVersion: apps/v1beta1
   kind: Deployment
   name: apptestlevilugato
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 85